0	29	.idea/codeStyles/Project.xml
1	0	app/src/main/AndroidManifest.xml
0	7	app/src/main/java/com/example/knocker/ContactAdapter.java
49	1	app/src/main/java/com/example/knocker/ContactSync.kt
1	1	app/src/main/java/com/example/knocker/MainActivity.kt
1	1	app/src/main/res/drawable/circle.xml
1	1	app/src/main/res/layout/content_contact_details.xml
29	0	.idea/codeStyles/Project.xml
1	1	.idea/misc.xml
0	229	app/src/main/java/com/example/knocker/NotifAdapter.java
218	0	app/src/main/java/com/example/knocker/NotifAdapter.kt
3	3	app/src/main/java/com/example/knocker/NotificationListener.kt
-	-	app/src/main/res/drawable-v24/aquarius.png
-	-	app/src/main/res/drawable/aquarius.png
6	6	app/src/main/res/layout/content_contact_details.xml
40	0	app/src/main/java/com/example/knocker/ContactSync.kt
22	79	app/src/main/java/com/example/knocker/MainActivity.kt
9	7	app/src/main/java/com/example/knocker/ContactAdapter.java
0	29	.idea/codeStyles/Project.xml
14	1	app/src/main/java/com/example/knocker/ContactInfo.kt
3	2	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
2	2	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
54	17	app/src/main/java/com/example/knocker/NotifAdapter.java
8	5	app/src/main/java/com/example/knocker/NotificationListener.kt
72	22	app/src/main/res/layout/activity_notification_adapter.xml
29	0	.idea/codeStyles/Project.xml
20	12	app/src/main/java/com/example/knocker/SettingsActivity.kt
39	15	app/src/main/res/layout/activity_settings.xml
7	4	app/src/main/java/com/example/knocker/MainActivity.kt
0	29	.idea/codeStyles/Project.xml
1	0	app/src/main/AndroidManifest.xml
33	0	app/src/main/java/com/example/knocker/ContactInfo.kt
1	1	app/src/main/java/com/example/knocker/ContactsPriority.kt
15	0	app/src/main/java/com/example/knocker/ContactAdapter.java
29	0	.idea/codeStyles/Project.xml
1	4	app/src/main/java/com/example/knocker/MainActivity.kt
3	1	app/src/main/java/com/example/knocker/NotifAdapter.java
11	7	app/src/main/java/com/example/knocker/NotificationListener.kt
1	1	.idea/misc.xml
15	3	app/schemas/com.example.knocker.ContactsRoomDatabase/5.json
149	0	app/schemas/com.example.knocker.ContactsRoomDatabase/6.json
8	1	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
6	3	app/src/main/java/com/example/knocker/NotificationListener.kt
3	1	app/src/main/java/com/example/knocker/NotificationDB.kt
2	2	app/src/main/res/layout/content_contact_details.xml
25	4	app/src/main/java/com/example/knocker/NotifAdapter.java
4	3	app/src/main/java/com/example/knocker/NotificationListener.kt
4	0	app/src/main/java/com/example/knocker/StatusBarParcelable.kt
42	50	app/src/main/res/layout/activity_add_new_contact.xml
14	14	app/src/main/res/layout/activity_notification_adapter.xml
0	29	.idea/codeStyles/Project.xml
4	0	.idea/encodings.xml
3	7	app/src/main/java/com/example/knocker/MainActivity.kt
19	4	app/src/main/java/com/example/knocker/SettingsActivity.kt
22	5	app/src/main/res/layout/activity_settings.xml
8	0	app/src/main/java/com/example/knocker/ChatActivity.java
395	0	app/src/main/java/com/example/knocker/CircularImageView.java
8	6	app/src/main/java/com/example/knocker/MainActivity.kt
1	1	app/src/main/res/drawable/ic_letter_k.xml
3	3	app/src/main/res/layout/activity_add_new_contact.xml
10	0	app/src/main/res/layout/activity_splash_screen.xml
1	1	app/src/main/res/layout/content_contact_details.xml
3	3	app/src/main/res/layout/content_main.xml
1	1	app/src/main/res/layout/grid_item_layout.xml
1	1	app/src/main/res/layout/nav_header_main.xml
19	0	app/src/main/res/values/attrs.xml
2	2	app/src/main/res/values/colors.xml
4	2	app/src/main/res/values/strings.xml
2	2	app/src/main/java/com/example/knocker/MainActivity.kt
6	4	app/src/main/java/com/example/knocker/NotificationListener.kt
6	4	app/src/main/res/layout/activity_add_new_contact.xml
15	3	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
19	6	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
36	15	app/src/main/java/com/example/knocker/EditContactActivity.kt
4	1	app/src/main/java/com/example/knocker/MainActivity.kt
7	6	app/src/main/java/com/example/knocker/NotificationListener.kt
59	0	app/src/main/java/com/example/knocker/NumberDB.kt
32	6	app/src/main/res/layout/content_contact_details.xml
2	1	app/src/main/res/values/colors.xml
14	2	app/src/main/java/com/example/knocker/ContactAdapter.java
3	2	app/src/main/java/com/example/knocker/MainActivity.kt
3	1	app/src/main/java/com/example/knocker/SettingsActivity.kt
15	13	app/src/main/java/com/example/knocker/MainActivity.kt
1	0	app/src/main/java/com/example/knocker/MainActivity.kt
2	11	app/src/main/java/com/example/knocker/MainActivity.kt
0	77	app/src/main/java/com/example/knocker/SettingsActivity.java
80	0	app/src/main/java/com/example/knocker/SettingsActivity.kt
1	1	app/src/main/java/com/example/knocker/SplashScreenActivity.kt
12	0	app/src/main/res/layout/activity_settings.xml
3	36	app/src/main/res/layout/activity_add_new_contact.xml
0	4	app/src/main/java/com/example/knocker/ContactsPriority.kt
12	1	app/src/main/java/com/example/knocker/ContactsPriority.kt
4	0	app/src/main/java/com/example/knocker/ContactsPriority.kt
20	14	app/src/main/java/com/example/knocker/NotificationListener.kt
149	110	app/src/main/res/layout/activity_add_new_contact.xml
1	1	app/src/main/java/com/example/knocker/ContactsPriority.kt
14	13	app/src/main/java/com/example/knocker/MainActivity.kt
3	2	app/src/main/res/layout/activity_add_new_contact.xml
3	0	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
21	5	app/src/main/java/com/example/knocker/EditContactActivity.kt
28	3	app/src/main/res/layout/activity_edit_contact.xml
7	5	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
15	1	app/src/main/java/com/example/knocker/ContactsPriority.kt
4	3	app/src/main/java/com/example/knocker/EditContactActivity.kt
3	1	app/src/main/java/com/example/knocker/NotifAdapter.java
49	17	app/src/main/java/com/example/knocker/MainActivity.kt
32	30	app/src/main/java/com/example/knocker/NotificationListener.kt
73	0	app/src/main/res/layout/alert_dialog_notification.xml
2	6	app/src/main/res/layout/activity_add_new_contact.xml
5	5	app/src/main/res/layout/activity_add_new_contact.xml
2	1	app/src/main/AndroidManifest.xml
37	0	app/src/main/java/com/example/knocker/ContactsPriority.kt
3	33	app/src/main/java/com/example/knocker/MainActivity.kt
33	0	app/src/main/java/com/example/knocker/MainActivity.kt
0	1	app/src/main/java/com/example/knocker/NotificationListener.kt
6	3	app/src/main/res/layout/activity_add_new_contact.xml
1	1	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
2	2	app/src/main/java/com/example/knocker/EditContactActivity.kt
5	0	app/build.gradle
9	5	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
4	4	app/src/main/java/com/example/knocker/ContactsDao.kt
8	8	app/src/main/java/com/example/knocker/EditContactActivity.kt
11	31	app/src/main/java/com/example/knocker/MainActivity.kt
27	3	app/src/main/res/layout/activity_add_new_contact.xml
5	0	app/src/main/java/com/example/knocker/NotifAdapter.java
7	2	app/src/main/java/com/example/knocker/NotificationListener.kt
0	1	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
0	4	app/src/main/java/com/example/knocker/EditContactActivity.kt
4	2	app/src/main/AndroidManifest.xml
6	2	app/src/main/java/com/example/knocker/EditContactActivity.kt
14	4	app/src/main/java/com/example/knocker/NotifAdapter.java
6	8	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
5	1	app/src/main/java/com/example/knocker/ContactsDao.kt
55	11	app/src/main/java/com/example/knocker/EditContactActivity.kt
18	11	app/src/main/java/com/example/knocker/NotifAdapter.java
6	2	app/src/main/java/com/example/knocker/NotificationListener.kt
137	0	app/schemas/com.example.knocker.ContactsRoomDatabase/5.json
58	19	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
19	2	app/src/main/java/com/example/knocker/ContactAdapter.java
41	16	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
2	1	app/src/main/java/com/example/knocker/ContactDB.kt
7	1	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
22	11	app/src/main/java/com/example/knocker/EditContactActivity.kt
2	2	app/src/main/java/com/example/knocker/MainActivity.kt
1	0	app/src/main/java/com/example/knocker/NotificationListener.kt
64	4	app/src/main/java/com/example/knocker/NotifAdapter.java
12	25	app/src/main/java/com/example/knocker/NotificationListener.kt
3	2	app/src/main/res/layout/activity_notification_adapter.xml
7	3	app/src/main/java/com/example/knocker/NotificationListener.kt
23	4	app/src/main/java/com/example/knocker/MainActivity.kt
48	2	app/src/main/java/com/example/knocker/ManageNotificationActivity.kt
5	2	app/src/main/java/com/example/knocker/NotificationListener.kt
1	1	app/src/main/java/com/example/knocker/SettingsActivity.java
34	4	app/src/main/res/layout/activity_manage_notification.xml
2	0	app/src/main/res/values/strings.xml
2	1	app/src/main/AndroidManifest.xml
12	0	app/src/main/java/com/example/knocker/ManageNotificationActivity.kt
0	39	app/src/main/java/com/example/knocker/NotificationAdapter.kt
13	5	app/src/main/java/com/example/knocker/NotificationListener.kt
9	0	app/src/main/java/com/example/knocker/SettingsActivity.java
27	0	app/src/main/res/layout/activity_manage_notification.xml
3	4	app/src/main/java/com/example/knocker/MainActivity.kt
20	3	app/src/main/java/com/example/knocker/NotificationListener.kt
22	4	app/schemas/com.example.knocker.ContactsRoomDatabase/3.json
131	0	app/schemas/com.example.knocker.ContactsRoomDatabase/4.json
1	1	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
2	1	app/src/main/java/com/example/knocker/ContactDB.kt
9	1	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
2	2	app/src/main/java/com/example/knocker/MainActivity.kt
3	1	app/src/main/java/com/example/knocker/NotificationDB.kt
7	4	app/src/main/AndroidManifest.xml
85	0	app/src/main/java/com/example/knocker/NotifAdapter.java
39	0	app/src/main/java/com/example/knocker/NotificationAdapter.kt
54	19	app/src/main/java/com/example/knocker/NotificationListener.kt
8	3	app/src/main/java/com/example/knocker/StatusBarParcelable.kt
8	0	app/src/main/res/drawable-v24/border_layout.xml
3	3	app/src/main/res/drawable-v24/{rounded_corner.xml => rounded_corner_dark_grey.xml}
16	0	app/src/main/res/drawable-v24/rounded_corner_light_grey.xml
82	0	app/src/main/res/layout/activity_notification_adapter.xml
27	42	app/src/main/res/layout/layout_notification_pop_up.xml
17	1	app/src/main/java/com/example/knocker/MainActivity.kt
21	13	app/src/main/java/com/example/knocker/MainActivity.kt
35	14	app/src/main/java/com/example/knocker/MainActivity.kt
0	2	app/src/main/java/com/example/knocker/NotificationListener.kt
30	4	app/src/main/java/com/example/knocker/MainActivity.kt
7	0	app/src/main/java/com/example/knocker/NotificationListener.kt
6	3	app/src/main/java/com/example/knocker/StatusBarParcelable.kt
0	7	.idea/misc.xml
1	3	.idea/vcs.xml
7	6	app/build.gradle
9	0	app/src/main/AndroidManifest.xml
64	0	app/src/main/java/com/example/knocker/MainActivity.kt
108	0	app/src/main/java/com/example/knocker/NotificationListener.kt
92	0	app/src/main/java/com/example/knocker/StatusBarParcelable.kt
-	-	app/src/main/res/drawable-v24/download.png
-	-	app/src/main/res/drawable-v24/facebook.png
-	-	app/src/main/res/drawable-v24/gmail.png
16	0	app/src/main/res/drawable-v24/rounded_corner.xml
-	-	app/src/main/res/drawable-v24/sms.png
81	0	app/src/main/res/layout/layout_notification_pop_up.xml
3	0	app/src/main/res/values/strings.xml
21	6	app/src/main/java/com/example/knocker/MainActivity.kt
11	10	app/src/main/res/menu/menu_main.xml
4	4	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
2	2	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
1	1	app/src/main/java/com/example/knocker/EditContactActivity.kt
4	3	app/src/main/java/com/example/knocker/MainActivity.kt
2	1	app/src/main/AndroidManifest.xml
2	2	app/src/main/res/values/strings.xml
1	1	app/src/main/java/com/example/knocker/ContactsDao.kt
27	1	app/src/main/java/com/example/knocker/MainActivity.kt
9	1	app/src/main/res/layout/content_main.xml
4	0	app/src/main/res/menu/menu_main.xml
12	0	app/src/main/java/com/example/knocker/ContactsDao.kt
17	1	app/src/main/java/com/example/knocker/NotificationsDao.kt
113	0	app/schemas/com.example.knocker.ContactsRoomDatabase/3.json
10	3	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
12	0	app/src/main/java/com/example/knocker/NotificationDB.kt
18	0	app/src/main/java/com/example/knocker/NotificationsDao.kt
20	4	app/src/main/java/com/example/knocker/ChatActivity.java
34	6	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
2	2	app/src/main/res/layout/activity_chat.xml
3	2	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
3	2	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
7	7	app/src/main/java/com/example/knocker/ContactDB.kt
1	0	app/src/main/java/com/example/knocker/DbWorkerThread.kt
8	1	app/src/main/java/com/example/knocker/MainActivity.kt
1	2	app/src/main/AndroidManifest.xml
1	2	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
5	0	app/src/main/java/com/example/knocker/EditContactActivity.kt
34	5	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
6	45	app/src/main/java/com/example/knocker/ChatActivity.java
13	0	app/src/main/res/layout/activity_chat.xml
7	13	app/src/main/AndroidManifest.xml
73	0	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
94	0	app/src/main/java/com/example/knocker/ChatActivity.java
68	13	app/src/main/java/com/example/knocker/EditContactActivity.kt
7	14	app/src/main/java/com/example/knocker/MainActivity.kt
22	0	app/src/main/res/layout/activity_chat.xml
44	25	app/src/main/java/com/example/knocker/MainActivity.kt
20	7	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
26	6	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
1	1	app/src/main/java/com/example/knocker/ContactAdapter.java
5	3	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
0	39	app/src/main/java/com/example/knocker/CustomDialogClass.kt
80	15	app/src/main/java/com/example/knocker/EditContactActivity.kt
0	86	app/src/main/java/com/example/knocker/RoundedImageView.java
12	0	app/src/main/res/drawable/circle.xml
4	0	app/src/main/res/drawable/ic_synchronization_arrows.xml
2	1	app/src/main/res/layout/activity_add_new_contact.xml
1	1	app/src/main/res/layout/activity_edit_contact.xml
1	1	app/src/main/res/layout/activity_main.xml
2	1	app/src/main/res/layout/content_contact_details.xml
0	55	app/src/main/res/layout/custom_popup.xml
1	1	app/src/main/res/layout/grid_item_layout.xml
1	1	app/src/main/res/layout/nav_header_main.xml
2	2	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
39	0	app/src/main/java/com/example/knocker/CustomDialogClass.kt
24	0	app/src/main/java/com/example/knocker/SplashScreenActivity.kt
55	0	app/src/main/res/layout/custom_popup.xml
4	0	app/src/main/res/values/strings.xml
33	38	app/src/main/java/com/example/knocker/MainActivity.kt
13	1	app/src/main/java/com/example/knocker/MainActivity.kt
-	-	app/src/main/res/drawable-v24/jf.jpg
-	-	app/src/main/res/drawable-v24/jl.png
-	-	app/src/main/res/drawable-v24/michel.png
0	5	app/src/main/res/drawable/ic_avatar.xml
0	4	app/src/main/res/drawable/ic_edit_button.xml
9	9	app/src/main/res/layout/activity_edit_contact.xml
14	0	app/src/main/res/layout/activity_main.xml
42	1	app/src/main/java/com/example/knocker/MainActivity.kt
5	0	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
6	0	app/src/main/java/com/example/knocker/MainActivity.kt
46	41	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
31	2	app/src/main/res/layout/activity_contact_details.xml
41	46	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
-	-	app/src/main/res/drawable-v24/jf.jpg
-	-	app/src/main/res/drawable-v24/jl.png
-	-	app/src/main/res/drawable-v24/michel.png
6	0	app/src/main/res/drawable/ic_about.xml
0	7	app/src/main/res/drawable/ic_delete.xml
2	31	app/src/main/res/layout/activity_contact_details.xml
4	0	app/src/main/res/menu/activity_main_drawer.xml
14	1	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
49	47	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
-	-	app/src/main/res/drawable-v24/jf.jpg
-	-	app/src/main/res/drawable-v24/jl.png
-	-	app/src/main/res/drawable-v24/michel.png
0	6	app/src/main/res/drawable/ic_about.xml
7	0	app/src/main/res/drawable/ic_delete.xml
31	2	app/src/main/res/layout/activity_contact_details.xml
0	4	app/src/main/res/menu/activity_main_drawer.xml
13	5	app/src/main/AndroidManifest.xml
0	18	app/src/main/java/com/example/knocker/ChatActivity.java
12	56	app/src/main/java/com/example/knocker/EditContactActivity.kt
4	3	app/src/main/java/com/example/knocker/MainActivity.kt
0	6	app/src/main/res/drawable/ic_warning.xml
0	30	app/src/main/res/layout/activity_chat.xml
0	62	app/src/main/res/layout/custom_popup.xml
0	6	app/src/main/res/values/strings.xml
5	13	app/src/main/AndroidManifest.xml
18	0	app/src/main/java/com/example/knocker/ChatActivity.java
56	12	app/src/main/java/com/example/knocker/EditContactActivity.kt
3	4	app/src/main/java/com/example/knocker/MainActivity.kt
6	0	app/src/main/res/drawable/ic_warning.xml
30	0	app/src/main/res/layout/activity_chat.xml
62	0	app/src/main/res/layout/custom_popup.xml
6	0	app/src/main/res/values/strings.xml
0	191	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
187	0	app/src/main/java/com/example/knocker/ContactDetailsActivity.kt
1	1	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
1	1	app/src/main/java/com/example/knocker/DbWorkerThread.kt
9	3	app/schemas/com.example.knocker.ContactsRoomDatabase/1.json
69	0	app/schemas/com.example.knocker.ContactsRoomDatabase/2.json
1	1	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
1	1	app/src/main/java/com/example/knocker/ContactDB.kt
2	2	app/src/main/java/com/example/knocker/ContactsDao.kt
10	2	app/src/main/java/com/example/knocker/ContactsRoomDatabase.kt
1	1	app/src/main/java/com/example/knocker/EditContactActivity.kt
1	0	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
2	2	app/src/main/java/com/example/knocker/ContactsDao.kt
11	10	app/src/main/java/com/example/knocker/EditContactActivity.kt
1	1	app/src/main/AndroidManifest.xml
8	14	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
20	8	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
1	0	app/src/main/java/com/example/knocker/ContactDB.kt
4	0	app/src/main/java/com/example/knocker/EditContactActivity.kt
2	0	app/src/main/java/com/example/knocker/MainActivity.kt
38	15	app/src/main/res/layout/content_contact_details.xml
7	1	app/src/main/res/values/strings.xml
2	2	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
0	86	app/src/main/java/com/example/knocker/EditContactActivity.java
105	0	app/src/main/java/com/example/knocker/EditContactActivity.kt
5	5	app/src/main/java/com/example/knocker/MainActivity.kt
39	13	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
4	6	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
4	0	app/src/main/res/drawable/ic_skype.xml
3	4	app/src/main/res/drawable/ic_twitter.xml
4	0	app/src/main/res/layout/activity_add_new_contact.xml
4	0	app/src/main/res/layout/activity_edit_contact.xml
23	16	app/src/main/res/layout/content_contact_details.xml
3	8	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
0	50	app/src/main/java/com/example/knocker/Contact.java
5	24	app/src/main/java/com/example/knocker/MainActivity.kt
0	4	app/src/main/java/com/example/knocker/User.java
8	8	app/src/main/java/com/example/knocker/ContactAdapter.java
13	13	app/src/main/java/com/example/knocker/MainActivity.kt
11	7	app/src/main/AndroidManifest.xml
8	15	app/src/main/java/com/example/knocker/ContactAdapter.java
65	25	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
23	18	app/src/main/java/com/example/knocker/MainActivity.kt
12	0	app/src/main/res/drawable/custom_edit_text.xml
20	15	app/src/main/res/layout/activity_add_new_contact.xml
9	5	app/src/main/res/layout/activity_edit_contact.xml
265	205	app/src/main/res/layout/content_contact_details.xml
1	0	app/src/main/res/values/colors.xml
1	0	app/src/main/res/values/dims.xml
4	0	app/src/main/res/values/strings.xml
6	0	app/src/main/res/xml/file_paths.xml
25	6	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
12	0	app/src/main/res/drawable/custom_edit_text.xml
20	15	app/src/main/res/layout/activity_add_new_contact.xml
9	5	app/src/main/res/layout/activity_edit_contact.xml
265	205	app/src/main/res/layout/content_contact_details.xml
1	0	app/src/main/res/values/colors.xml
1	0	app/src/main/res/values/dims.xml
4	0	app/src/main/res/values/strings.xml
0	68	app/src/main/java/com/example/knocker/AddNewContactActivity.java
88	0	app/src/main/java/com/example/knocker/AddNewContactActivity.kt
7	0	app/src/main/java/com/example/knocker/MainActivity.kt
26	4	app/src/main/java/com/example/knocker/AddNewContactActivity.java
43	10	app/src/main/java/com/example/knocker/EditContactActivity.java
2	2	app/src/main/res/layout/activity_add_new_contact.xml
3	3	app/src/main/res/layout/activity_edit_contact.xml
1	1	app/src/main/res/menu/menu_add_contact.xml
0	0	app/src/main/java/com/example/knocker/{DataClass.kt => ContactDB.kt}
16	0	app/src/main/java/com/example/knocker/ContactsDao.kt
1	1	app/src/main/java/com/example/knocker/DataClass.kt
3	3	app/src/main/java/com/example/knocker/MainActivity.kt
0	15	app/src/main/java/com/example/knocker/EditProfilActivity.java
0	9	app/src/main/res/layout/activity_edit_profil.xml
53	0	app/src/main/java/com/example/knocker/EditContactActivity.java
5	5	app/src/main/java/com/example/knocker/MainActivity.kt
124	0	app/src/main/res/layout/activity_edit_contact.xml
1	1	app/src/main/res/layout/content_contact_details.xml
26	0	app/src/main/res/values/strings.xml
2	2	app/src/main/java/com/example/knocker/MainActivity.kt
15	3	app/schemas/com.example.knocker.ContactsRoomDatabase/1.json
8	1	app/src/main/AndroidManifest.xml
3	10	app/src/main/java/com/example/knocker/Contact.java
15	8	app/src/main/java/com/example/knocker/ContactAdapter.java
56	1	app/src/main/java/com/example/knocker/ContactDetailsActivity.java
2	2	app/src/main/java/com/example/knocker/DataClass.kt
